# Generated by Django 6.0.6 on 2026-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_commentary_updated_at_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
