/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Task Tracker App API
 * Task Tracker App
 * OpenAPI spec version: 1.0.0
 */

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export interface User {
  readonly id: number;
  /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
  readonly username: string;
}

export interface CommentaryRead {
  readonly id: number;
  readonly author: User;
  text: string;
  readonly created_at: string;
}

export interface CommentaryWrite {
  task: number;
  text: string;
}

/**
 * * `0` - In Progress
 * * `1` - Finished
 */
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


export const StatusEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;

export interface PatchedTaskWriteSerializer {
  readonly id?: number;
  title?: string;
  description?: string;
  /** @nullable */
  created_by?: number | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  /** @nullable */
  assigned_to?: number | null;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  status?: StatusEnum;
}

export interface TaskReadSerializer {
  readonly id: number;
  title: string;
  description?: string;
  readonly created_by: User;
  readonly created_at: string;
  readonly updated_at: string;
  assigned_to: User;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  status?: StatusEnum;
  readonly status_display: string;
}

export interface TaskWriteSerializer {
  readonly id: number;
  title: string;
  description?: string;
  /** @nullable */
  created_by?: number | null;
  readonly created_at: string;
  readonly updated_at: string;
  /** @nullable */
  assigned_to?: number | null;
  /**
     * @minimum -9223372036854776000
     * @maximum 9223372036854776000
     */
  status?: StatusEnum;
}

export type CommentariesListParams = {
/**
 * Id of task for which to get comments.
 */
task_id: number;
};

export type commentariesListResponse200 = {
  data: CommentaryRead[]
  status: 200
}

export type commentariesListResponseSuccess = (commentariesListResponse200) & {
  headers: Headers;
};
;

export type commentariesListResponse = (commentariesListResponseSuccess)

export const getCommentariesListUrl = (params: CommentariesListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/commentaries/?${stringifiedParams}` : `/commentaries/`
}

/**
 * API endpoint for Commentary CRUD operations.
 */
export const commentariesList = async (params: CommentariesListParams, options?: RequestInit): Promise<commentariesListResponse> => {

  const res = await fetch(getCommentariesListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commentariesListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentariesListResponse
}



export type commentariesCreateResponse201 = {
  data: CommentaryWrite
  status: 201
}

export type commentariesCreateResponseSuccess = (commentariesCreateResponse201) & {
  headers: Headers;
};
;

export type commentariesCreateResponse = (commentariesCreateResponseSuccess)

export const getCommentariesCreateUrl = () => {




  return `/commentaries/`
}

/**
 * API endpoint for Commentary CRUD operations.
 */
export const commentariesCreate = async (commentaryWrite: CommentaryWrite, options?: RequestInit): Promise<commentariesCreateResponse> => {

  const res = await fetch(getCommentariesCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(commentaryWrite)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commentariesCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentariesCreateResponse
}



export type commentariesRetrieveResponse200 = {
  data: CommentaryRead
  status: 200
}

export type commentariesRetrieveResponseSuccess = (commentariesRetrieveResponse200) & {
  headers: Headers;
};
;

export type commentariesRetrieveResponse = (commentariesRetrieveResponseSuccess)

export const getCommentariesRetrieveUrl = (id: number,) => {




  return `/commentaries/${id}/`
}

/**
 * API endpoint for Commentary CRUD operations.
 */
export const commentariesRetrieve = async (id: number, options?: RequestInit): Promise<commentariesRetrieveResponse> => {

  const res = await fetch(getCommentariesRetrieveUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commentariesRetrieveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commentariesRetrieveResponse
}



export type tasksListResponse200 = {
  data: TaskReadSerializer[]
  status: 200
}

export type tasksListResponseSuccess = (tasksListResponse200) & {
  headers: Headers;
};
;

export type tasksListResponse = (tasksListResponseSuccess)

export const getTasksListUrl = () => {




  return `/tasks/`
}

/**
 * API endpoint for Task CRUD operations.
 */
export const tasksList = async ( options?: RequestInit): Promise<tasksListResponse> => {

  const res = await fetch(getTasksListUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tasksListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tasksListResponse
}



export type tasksCreateResponse201 = {
  data: TaskWriteSerializer
  status: 201
}

export type tasksCreateResponseSuccess = (tasksCreateResponse201) & {
  headers: Headers;
};
;

export type tasksCreateResponse = (tasksCreateResponseSuccess)

export const getTasksCreateUrl = () => {




  return `/tasks/`
}

/**
 * API endpoint for Task CRUD operations.
 */
export const tasksCreate = async (TaskWriteSerializer: NonReadonly<TaskWriteSerializer>, options?: RequestInit): Promise<tasksCreateResponse> => {

  const res = await fetch(getTasksCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(TaskWriteSerializer)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tasksCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tasksCreateResponse
}



export type tasksRetrieveResponse200 = {
  data: TaskReadSerializer
  status: 200
}

export type tasksRetrieveResponseSuccess = (tasksRetrieveResponse200) & {
  headers: Headers;
};
;

export type tasksRetrieveResponse = (tasksRetrieveResponseSuccess)

export const getTasksRetrieveUrl = (id: number,) => {




  return `/tasks/${id}/`
}

/**
 * API endpoint for Task CRUD operations.
 */
export const tasksRetrieve = async (id: number, options?: RequestInit): Promise<tasksRetrieveResponse> => {

  const res = await fetch(getTasksRetrieveUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tasksRetrieveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tasksRetrieveResponse
}



export type tasksUpdateResponse200 = {
  data: TaskWriteSerializer
  status: 200
}

export type tasksUpdateResponseSuccess = (tasksUpdateResponse200) & {
  headers: Headers;
};
;

export type tasksUpdateResponse = (tasksUpdateResponseSuccess)

export const getTasksUpdateUrl = (id: number,) => {




  return `/tasks/${id}/`
}

/**
 * API endpoint for Task CRUD operations.
 */
export const tasksUpdate = async (id: number,
    TaskWriteSerializer: NonReadonly<TaskWriteSerializer>, options?: RequestInit): Promise<tasksUpdateResponse> => {

  const res = await fetch(getTasksUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(TaskWriteSerializer)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tasksUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tasksUpdateResponse
}



export type tasksPartialUpdateResponse200 = {
  data: TaskWriteSerializer
  status: 200
}

export type tasksPartialUpdateResponseSuccess = (tasksPartialUpdateResponse200) & {
  headers: Headers;
};
;

export type tasksPartialUpdateResponse = (tasksPartialUpdateResponseSuccess)

export const getTasksPartialUpdateUrl = (id: number,) => {




  return `/tasks/${id}/`
}

/**
 * API endpoint for Task CRUD operations.
 */
export const tasksPartialUpdate = async (id: number,
    patchedTaskWriteSerializer?: NonReadonly<PatchedTaskWriteSerializer>, options?: RequestInit): Promise<tasksPartialUpdateResponse> => {

  const res = await fetch(getTasksPartialUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchedTaskWriteSerializer)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tasksPartialUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tasksPartialUpdateResponse
}



export type tasksDestroyResponse204 = {
  data: void
  status: 204
}

export type tasksDestroyResponseSuccess = (tasksDestroyResponse204) & {
  headers: Headers;
};
;

export type tasksDestroyResponse = (tasksDestroyResponseSuccess)

export const getTasksDestroyUrl = (id: number,) => {




  return `/tasks/${id}/`
}

/**
 * API endpoint for Task CRUD operations.
 */
export const tasksDestroy = async (id: number, options?: RequestInit): Promise<tasksDestroyResponse> => {

  const res = await fetch(getTasksDestroyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tasksDestroyResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as tasksDestroyResponse
}



export type usersListResponse200 = {
  data: User[]
  status: 200
}

export type usersListResponseSuccess = (usersListResponse200) & {
  headers: Headers;
};
;

export type usersListResponse = (usersListResponseSuccess)

export const getUsersListUrl = () => {




  return `/users/`
}

/**
 * API endpoint that allows users to be viewed
 */
export const usersList = async ( options?: RequestInit): Promise<usersListResponse> => {

  const res = await fetch(getUsersListUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersListResponse
}



export type usersRetrieveResponse200 = {
  data: User
  status: 200
}

export type usersRetrieveResponseSuccess = (usersRetrieveResponse200) & {
  headers: Headers;
};
;

export type usersRetrieveResponse = (usersRetrieveResponseSuccess)

export const getUsersRetrieveUrl = (id: number,) => {




  return `/users/${id}/`
}

/**
 * API endpoint that allows users to be viewed
 */
export const usersRetrieve = async (id: number, options?: RequestInit): Promise<usersRetrieveResponse> => {

  const res = await fetch(getUsersRetrieveUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersRetrieveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersRetrieveResponse
}
